apiVersion: v1
kind: Service
metadata:
  name: demo-app-service
  labels:
    app: demo-app
  namespace: k8s-test

spec:
  ports:
    - name : tcp-protocol
      port: 80
      protocol: TCP
      targetPort: 8000
      nodePort: 30007
  selector:
    app: demo-app
  type: NodePort
