apiVersion: v1
kind: Service
metadata:
  name: demo-app-service
  labels:
    app: demo-app
  namespace: k8s-test

spec:
  type: NodePort
  selector:
    app: demo-app  
  ports:
    - name : tcp-protocol
      protocol: TCP
      targetPort: 8000
      port: 80
      nodePort: 30007
